apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: g3p2
  region: us-west-1
  version: "1.21"

availabilityZones: [us-west-1a, us-west-1c]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true