apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: g3p2
  region: us-west-1
  version: "1.21"

subnets: [g3p2-PublicSubnet02, g3p2-PublicSubnet01]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true